export const GET_EPISODE = "EPS/EPISODE/LOAD";
export const GET_EPISODE_SUCCESS = "EPS/EPISODE/LOAD_SUCCESS";
export const GET_EPISODE_FAIL = "EPS/EPISODE/LOAD_FAIL";
export const GET_EPISODE_URL = "/episode";

export const GET_EPISODE_DETAIL = "EPSD/EPISODE_DETAIL/LOAD";
export const GET_EPISODE_DETAIL_SUCCESS = "EPSD/EPISODE_DETAIL/LOAD_SUCCESS";
export const GET_EPISODE_DETAIL_FAIL = "EPSD/EPISODE_DETAIL/LOAD_FAIL";
export const GET_EPISODE_DETAIL_URL = "/episode/";
